# Generated by Django 5.2.17 on 2026-09-27 08:07

import datetime

import django.db.models.deletion
from django.db import migrations, models

import listings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Listing type",
                "verbose_name_plural": "Listing types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Price"
                    ),
                ),
                (
                    "ceiling_height",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ceiling height"
                    ),
                ),
                ("bedrooms", models.PositiveIntegerField(verbose_name="Bedrooms")),
                ("bathrooms", models.PositiveIntegerField(verbose_name="Bathrooms")),
                (
                    "garage",
                    models.PositiveIntegerField(default=0, verbose_name="Garage"),
                ),
                ("sqft", models.PositiveIntegerField(verbose_name="Area (m²)")),
                (
                    "lot_size",
                    models.FloatField(blank=True, null=True, verbose_name="Lot size"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        upload_to=listings.models.listing_dir_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "listing_for",
                    models.CharField(
                        choices=[("R", "Rent"), ("S", "Sell")],
                        default="S",
                        max_length=1,
                        verbose_name="Listing for",
                    ),
                ),
                (
                    "protected",
                    models.BooleanField(
                        default=False, verbose_name="Monument protected"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="Online"),
                ),
                (
                    "free_from",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        verbose_name="Free from",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("latitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("longitude", models.FloatField(blank=True, db_index=True, null=True)),
                ("geocoded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="core.address",
                        verbose_name="Address",
                    ),
                ),
                (
                    "realtor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="accounts.realtor",
                        verbose_name="Realtor",
                    ),
                ),
                (
                    "listing_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="listings.listingtype",
                        verbose_name="Listing type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing",
                "verbose_name_plural": "Listings",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=listings.models.listing_dir_path,
                        verbose_name="Image",
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Short description"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listingimage_set",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing image",
                "verbose_name_plural": "Listing images",
                "ordering": ["created"],
            },
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-created"], name="listings_li_created_e91fac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["is_published", "-created"],
                name="listings_li_is_publ_7fa577_idx",
            ),
        ),
    ]
