# Generated by Django 5.2.17 on 2026-09-27 08:07

import django.db.models.deletion
from django.db import migrations, models

import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListingFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Short description"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=documents.models.listing_file_dir_path,
                        validators=[
                            documents.models.validate_document_extension,
                            documents.models.validate_document_size,
                        ],
                        verbose_name="File",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                (
                    "for_customer",
                    models.BooleanField(default=False, verbose_name="For customers"),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listingfile_set",
                        to="listings.listing",
                        verbose_name="Listing",
                    ),
                ),
            ],
            options={
                "verbose_name": "Listing document",
                "verbose_name_plural": "Listing documents",
                "ordering": ["-created"],
            },
        ),
    ]
